image: jangrewe/gitlab-ci-android

cache:
  - key: "build-number"
    paths:
      - build-number

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebug

deployToFirebase:
  stage: deploy
  script:
    - touch build-number
    - VERSION_RUNNER=$ANDROID_BUILD_NUMBER
    - test -s build-number && VERSION_RUNNER=$(<build-number)
    - >
      test $VERSION_RUNNER -lt $VERSION_PROJECT
      && echo $((++VERSION_PROJECT))> build-number
      || echo $((++VERSION_RUNNER))> build-number
    - export BUILD_NUMBER=$(<build-number)
    - echo $BUILD_NUMBER
    - touch last-build-hash
    - ./gradlew assembleQa appDistributionUploadQa --artifactType="APK"
  artifacts:
    paths:
      - ./app/build/outputs/bundle/aa/app-qa.apk
    when: on_success
    expire_in: 2 week
  when: manual